ThisBuild / version := "0.1.0-SNAPSHOT"

ThisBuild / scalaVersion := "2.13.11"

name := "SaratLearn"

version := "1.0"

scalaVersion := "2.11.12"
//libraryDependencies += "org.apache.spark" %% "spark-core" % "1.6.3"
libraryDependencies += "org.apache.spark" %% "spark-core" % "2.2.0"
//libraryDependencies += "org.apache.spark" %% "spark-core" % "2.1.0"
//libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.4.5"
libraryDependencies += "org.apache.spark" %% "spark-sql" % "2.2.0"
libraryDependencies += "org.apache.commons" % "commons-csv" % "1.2"
libraryDependencies += "org.eclipse.jetty" % "jetty-client" % "8.1.14.v20131031"
libraryDependencies += "com.snowflake" % "snowpark" % "1.8.0"
libraryDependencies += "net.snowflake" % "snowflake-ingest-sdk" % "0.10.8"
libraryDependencies += "net.snowflake" % "snowflake-jdbc" % "3.13.3"
//libraryDependencies += "net.snowflake" % "spark-snowflake_2.12" % "2.9.0-spark_2.4"
libraryDependencies += "net.snowflake" %% "spark-snowflake" % "2.9.0-spark_2.4"
//libraryDependencies += "net.snowflake" % "snowflake-common" % "5.1.2"
//libraryDependencies += "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.15.0"
libraryDependencies += "com.fasterxml.jackson.module" %% "jackson-module-scala" % "2.15.2"
//libraryDependencies += "com.fasterxml.jackson.core" % "jackson-databind" % "2.13.5"
libraryDependencies += "com.microsoft.sqlserver" % "mssql-jdbc" % "10.2.3.jre11"
libraryDependencies += "com.microsoft.azure" % "spark-mssql-connector" % "1.0.2"
libraryDependencies += "mysql" % "mysql-connector-java" % "8.0.13"